# Generated by Django 6.0.4 on 2026-04-21 10:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full legal name.', max_length=60)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='10-digit Nepali mobile number starting with 97 or 98.', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 97 or 98 (e.g. 9841234567).', regex='^(97|98)\\d{8}$')])),
                ('previous_institute', models.CharField(blank=True, help_text='Name of previously attended school/college.', max_length=200)),
                ('current_level', models.CharField(blank=True, choices=[('plus_two', '+2 (Grade XI/XII)'), ('bachelors', 'Bachelors'), ('masters', 'Masters')], max_length=20, null=True)),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Students MUST have this True to log in.')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Optional | does not block login.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='pages.course')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='MailQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, help_text='HTML email body.')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail Queue',
                'verbose_name_plural': 'Mail Queue',
                'indexes': [models.Index(fields=['status'], name='cauth_mailq_status_80abc0_idx'), models.Index(fields=['to_email'], name='cauth_mailq_to_emai_43089c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 97 or 98 (e.g. 9841234567).', regex='^(97|98)\\d{8}$')])),
                ('message', models.CharField(help_text='Max 160 chars for a single SMS segment.', max_length=160)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Queue',
                'verbose_name_plural': 'SMS Queue',
                'indexes': [models.Index(fields=['status'], name='cauth_smsqu_status_640226_idx'), models.Index(fields=['to_phone'], name='cauth_smsqu_to_phon_1dfa49_idx')],
            },
        ),
    ]
