# Generated by Django 6.0.4 on 2026-05-27 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0002_smsqueue_sent_at_alter_smsqueue_message_and_more'),
        ('pages', '0003_section_lecture_subject_section_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='pages.course', to_field='slug'),
        ),
    ]
