# Generated by Django 6.0.4 on 2026-06-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0003_alter_user_interested_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
