# Generated by Django 6.0.4 on 2026-06-03 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0004_emailtoken_used_at_passwordresettoken_used_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsqueue',
            name='to_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits starting with 97 or 98 (e.g. 9841234567).', regex='^(97|98)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits starting with 97 or 98 (e.g. 9841234567).', regex='^(97|98)\\d{8}$')]),
        ),
    ]
