# Generated by Django 5.2.8 on 2026-05-29 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_alter_course_id_alter_enrollment_id_alter_lecture_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Optional label, e.g. 'Passage 1'.", max_length=255)),
                ('content', models.TextField(help_text='HTML / LaTeX / code — rendered in exam view.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Supports HTML / LaTeX / images.')),
                ('instructions', models.TextField(blank=True, help_text='Shown on the exam start page.')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no hard deadline.', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Personal time-limit in minutes. Leave blank for unlimited.', null=True)),
                ('make_public', models.BooleanField(default=False, help_text='Always visible regardless of dates (e.g. practice exam).')),
                ('make_public_after', models.BooleanField(default=False, help_text='Allow students to attempt the exam even after end_date.')),
                ('correct_marks', models.FloatField(default=1.0, help_text='Marks per correct answer.')),
                ('negative_marks', models.FloatField(default=0.0, help_text='Marks deducted per wrong answer (positive value).')),
                ('has_negative_marking', models.BooleanField(default=False)),
                ('result_mode', models.CharField(choices=[('hidden', 'Hidden — Never show results'), ('after_end', 'After End — Show once exam ends'), ('auto', 'Scheduled — Show at specific date/time'), ('manual', 'Manual — Admin toggles visibility')], default='after_end', max_length=20)),
                ('result_publish_time', models.DateTimeField(blank=True, help_text="Only used when result_mode = 'auto'.", null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='pages.course')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('negative_score', models.FloatField(default=0.0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('unattempted_count', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('override_scoring', models.BooleanField(default=False, help_text='Override exam-level scoring rules for this section.')),
                ('custom_correct_marks', models.FloatField(blank=True, null=True)),
                ('custom_negative_marks', models.FloatField(blank=True, null=True)),
                ('custom_has_negative', models.BooleanField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exam.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('title', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Supports LaTeX ($$...$$), HTML, <pre> code blocks.')),
                ('option_one', models.TextField(blank=True)),
                ('option_two', models.TextField(blank=True)),
                ('option_three', models.TextField(blank=True)),
                ('option_four', models.TextField(blank=True)),
                ('correct_option', models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=1, null=True)),
                ('explanation', models.TextField(blank=True, help_text='Shown after results are published. Supports HTML / LaTeX.')),
                ('marks', models.FloatField(default=1.0)),
                ('use_custom_marks', models.BooleanField(default=False, help_text="Use this question's marks instead of section/exam defaults.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam')),
                ('paragraph', models.ForeignKey(blank=True, help_text='Link to a reading passage if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exam.paragraph')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.section')),
            ],
            options={
                'ordering': ['section__order', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='paragraph',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='exam.section'),
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=1, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='exam.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.question')),
            ],
            options={
                'unique_together': {('exam_attempt', 'question')},
            },
        ),
    ]
