# Generated by Django 6.0.4 on 2026-05-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_course_id_alter_enrollment_id_alter_lecture_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(blank=True, help_text='Supports HTML. Notice body.')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload result sheets or notice PDF.', null=True, upload_to='notices/')),
                ('meta_title', models.CharField(blank=True, help_text='For SEO. Leave blank to use notice title.', max_length=150)),
                ('meta_description', models.CharField(blank=True, help_text='For SEO description.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='For SEO keywords, comma separated.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Saral Pathshala', max_length=100)),
                ('site_title', models.CharField(default='Saral Pathshala - Online MCQ & Lectures Portal', max_length=200)),
                ('site_description', models.TextField(blank=True, default="Saral Pathshala is Nepal's leading e-learning platform providing course details, lectures, and online exams.")),
                ('meta_keywords', models.CharField(blank=True, default='BSC.CSIT, CSIT, CEE, IOE, Nepal, e-learning, exam preparation', max_length=255)),
                ('contact_email', models.EmailField(default='info@saralpathshala.com', max_length=254)),
                ('contact_phone', models.CharField(default='9841234567', max_length=15)),
                ('contact_address', models.CharField(default='Kathmandu, Nepal', max_length=200)),
                ('whatsapp_number', models.CharField(default='9841234567', max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('social_facebook', models.URLField(blank=True, default='https://facebook.com/saralpathshala')),
                ('social_twitter', models.URLField(blank=True, default='https://twitter.com/saralpathshala')),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com/saralpathshala')),
                ('social_tiktok', models.URLField(blank=True, default='https://tiktok.com/@saralpathshala')),
                ('social_linkedin', models.URLField(blank=True, default='https://linkedin.com/company/saralpathshala')),
                ('social_threads', models.URLField(blank=True, default='https://threads.net/@saralpathshala')),
                ('google_analytics_id', models.CharField(blank=True, default='G-XXXXXXXXXX', max_length=50)),
                ('akash_sms_auth_token', models.CharField(blank=True, default='YOUR_AKASH_SMS_TOKEN', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CourseEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved / Enrolled'), ('contacted', 'Contacted / Followed Up'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='pages.course')),
            ],
            options={
                'verbose_name': 'Enrollment Request',
                'verbose_name_plural': 'Enrollment Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
